# Generated by Django 5.2.7 on 2025-10-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_price_currency',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='type',
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('SHARE', 'Share'), ('OPTION', 'Option'), ('KO', 'Knockout'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=16),
        ),
    ]
