# Generated by Django 5.2.7 on 2025-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_remove_asset_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('OPTION', 'Option'), ('KO', 'Knockout'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=16),
        ),
    ]
