# Generated by Django 5.2.7 on 2025-10-10 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0002_remove_asset_current_price_and_more'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('executed_at', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
