# Generated by Django 5.2.7 on 2025-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_costs',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
